# Generated by Django 3.1.1 on 2020-10-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyfinder', '0008_userprofile_hide_state'),
        ('studybuddyfinder', '0006_auto_20201022_1252'),
    ]

    operations = [
    ]
