# Generated by Django 3.1.1 on 2020-11-02 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyfinder', '0011_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hide_username',
        ),
    ]
