# Generated by Django 3.1.1 on 2020-11-03 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyfinder', '0012_remove_userprofile_hide_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, null=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='studybuddyfinder.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='announcements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='studybuddyfinder.announcement'),
        ),
    ]
