# Generated by Django 3.1.1 on 2020-11-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyfinder', '0013_auto_20201103_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='announcements',
        ),
        migrations.AddField(
            model_name='group',
            name='announcements',
            field=models.ManyToManyField(blank=True, to='studybuddyfinder.Announcement'),
        ),
    ]
