# Generated by Django 3.1.1 on 2020-11-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyfinder', '0015_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coure_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
