# Generated by Django 3.1.1 on 2020-11-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyfinder', '0016_course_coure_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coure_number',
            new_name='course_number',
        ),
    ]
