# Generated by Django 3.1.1 on 2020-11-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyfinder', '0017_auto_20201108_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
