# Generated by Django 3.1.1 on 2020-11-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyfinder', '0018_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uva_courses',
            field=models.ManyToManyField(blank=True, to='studybuddyfinder.Course'),
        ),
    ]
