# Generated by Django 3.1.1 on 2020-11-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyfinder', '0019_userprofile_uva_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(choices=[('Aerospace Engineering', 'Aerospace Engineering'), ('African American and African Studies', 'African American and African Studies'), ('Anthropology', 'Anthropology'), ('Archaeology', 'Archaeology'), ('Arichtectural History', 'Arichtectural History'), ('Architecture', 'Architecture'), ('Astronomy', 'Astronomy'), ('Biology', 'Biology'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Civil Engineering', 'Civil Engineering'), ('Classics', 'Classics'), ('Cognitive Science', 'Cognitive Science'), ('Commerce', 'Commerce'), ('Comparative Literature', 'Comparative Literature'), ('Computer Engineering', 'Computer Engineering'), ('Computer Science', 'Computer Science'), ('Dance', 'Dance'), ('Drama', 'Drama'), ('East Asian Languages', 'East Asian Languages'), ('Economics', 'Economics'), ('Electical Engineering', 'Electrical Engineering'), ('English', 'English'), ('Environmental Sciences', 'Environmental Science'), ('French', 'French'), ('German', 'German'), ('German Studies', 'German Studies'), ('Global Studies', 'Global Studies'), ('History', 'History'), ('History of Art', 'History of Art'), ('Human Biology', 'Human Biology'), ('Jewish Studies', 'Jewish Studies'), ('Kinesiology', 'Kinesiology'), ('Latin American Studies', 'Latin American Studies'), ('Linguistics', 'Linguistics'), ('Materials Science and Engineering', 'Materials Science and Engineering'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Media Studies', 'Media Studies'), ('South Asian Languages', 'South Asian Languages'), ('Music', 'Music'), ('Neuroscience', 'Neuroscience'), ('Nursing', 'Nursing'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political and Social Thought', 'Political and Social Thought'), ('Politics', 'Politics'), ('Psychology', 'Psychology'), ('Religious Studies', 'Religious Studies'), ('Slavic Languages and Literature', 'Slavic Languages and Literature'), ('Sociology', 'Sociology'), ('Spanish', 'Spanish'), ('Statistics', 'Statistics'), ('Studio Art', 'Studio Art'), ('Systems Engineering', 'Systems Engineering'), ('Urban and Environmental Planning', 'Urban and Environmental Planning'), ('Women, Gender, and Sexuality', 'Women, Gender, and Sexuality')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(choices=[('College of Arts & Sciences', 'College of Arts & Sciences'), ('School of Engineering and Applied Science', 'School of Engineering and Applied Science'), ('McIntire School of Commerce', 'McIntire School of Commerce'), ('Frank Batten School of Leadership and Public Policy', 'Frank Batten School of Leadership and Public Policy'), ('School of Architecture', 'School of Architecture'), ('School of Data Science', 'School of Data Science'), ('Darden School of Business', 'Darden School of Business'), ('School of Law', 'School of Law'), ('School of Medicine', 'School of Medicine'), ('Graduate School of Arts & Sciences', 'Graduate School of Arts & Sciences'), ('School of Nursing', 'School of Nursing'), ('School of Continuing & Professional Studies', 'School of Continuing & Professional Studies'), ('School of Education and Human Development', 'School of Education and Human Development')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('Virginia', 'Virginia'), ('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('American Samoa', 'American Samoa'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('District of Colombia', 'District of Colombia'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Guam', 'Guam'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachussets', 'Massachussets'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Puerto Rico', 'Puerto Rico'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennesse', 'Tennessee'), ('Texas', 'Texas'), ('US Virgin Islands', 'US Virgin Islands'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=100, null=True),
        ),
    ]
