# Generated by Django 3.1.1 on 2020-11-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyfinder', '0022_userprofile_bio'),
        ('studybuddyfinder', '0020_auto_20201109_2321'),
    ]

    operations = [
    ]
