# Generated by Django 3.1.1 on 2020-11-10 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyfinder', '0021_auto_20201110_2104'),
        ('studybuddyfinder', '0023_merge_20201110_0153'),
    ]

    operations = [
    ]
