# Generated by Django 3.1.1 on 2020-11-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyfinder', '0024_merge_20201110_2353'),
        ('studybuddyfinder', '0025_auto_20201112_1840'),
    ]

    operations = [
    ]
