# Generated by Django 3.1.1 on 2020-11-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyfinder', '0026_merge_20201113_0411'),
        ('studybuddyfinder', '0026_merge_20201113_0142'),
    ]

    operations = [
    ]
